Login/Login/Controllers/EntrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login.Controllers
{
    public class EntrarController : Controller
    {
        // GET: Entrar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PageEntrar()
        {
     
            return RedirectToAction("Index", "Login");

        }
    }
}

Login/Login/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Login.Models;

namespace Login.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Autherize(Login.Models.Cliente clienteModel)
        {
            using(teachmeDB db = new teachmeDB())
            {
                var clientDetails = db.Cliente.Where( x => x.Email == clienteModel.Email && x.Password == clienteModel.Password).FirstOrDefault();
                if (clientDetails == null)
                {
                   // clienteModel.LoginMessageError = "Mail ou password incorretos";
                    return View("Index", clienteModel);

                }
                else
                {
                    Session["clientID"] = clientDetails.ID;
                    Session["clientName"] = clientDetails.Nome;
                    return RedirectToAction("Index", "Home");
                }
            }
        }

        public ActionResult LogOut()
        {
            int clientId = (int)Session["clientID"];
            Session.Abandon();
            return RedirectToAction("Index","Login");

        }

        
    }
}

Login/Login/Views/Login/Index.cshtml
@model Login.Models.Cliente
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/normalize.css">
    <title>TeachMe | Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: 'Open Sans', sans-serif;
        }

       
        a {
            text-decoration: none;
        }

        header {
            top: 0;
            position: fixed;
            float: left;
            margin: 0 0 30px 0;
            padding: 5px 0 0 0;
            width: 100%;
        }

        #logo {
            text-align: center;
            margin: 0;
        }


        nav {
            text-align: center;
            padding: 10px 0;
            margin: 30px 0 0;
        }

        nav ul {
            list-style: none;
            margin: 0 10px;
            padding: 0;
        }

        #form-div {
            max-width: 400px;
            margin: 0 auto;
            padding: 20% 5%;

        }

            nav li {
                display: inline-block;
            }

            nav a {
                font-weight: 800;
                padding: 15px 10px;
            }
        /* site body */
        body {
            background-color: whitesmoke;
        }  

        /* green header */
        header {
            background: #6ab47b;
            border-color: #599a68;
        }

        /* nav background on mobile */
        nav {
            background: #599a68;
        }

            /* nav link */
        nav a, nav a:visited {
           color: #fff;
        }

                /* selected nav link */
       nav a.selected, nav a:hover {
             color: #32673f;
      }

        /* links */
        a {
            color: #6ab47b;
        }

        img {
            display: block;
            padding-top: 1%;
            margin-left: auto;
            margin-right: auto;
            width: 10%;
        }
  
     
    </style>
</head>
<body>
    <header>
        <a href="index.html" id="logo">
            <img src="~/css/logo_new.png" alt="">
        </a>
        <nav>
            <ul>
                <li><a href="@Url.Action("PageComoFunciona","ComoFunciona")">Como Funciona</a></li>
                <li><a href="@Url.Action("PageEquipa","Equipa")">Equipa</a></li>
                <li><a href="@Url.Action("PageContacto","Contacto")">Contacto</a></li>
                <li><a href="@Url.Action("PageEntrar","Entrar")">Entrar</a></li>
                <li><a href="@Url.Action("PageInscrisao","Inscrisao")">Inscrisão</a></li>
            </ul>
        </nav>
    </header>
    <section id="form-div">
        @using (Html.BeginForm("Autherize", "Login", FormMethod.Post))
        {
            <table>
                <tr>
                    <td></td>
                    <td>Entrar</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Email)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Email)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Password)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Password)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Password)</td>
                </tr>
             
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="name" value="Login" />
                    </td>
                </tr>
            </table>

        }

    </section>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

</body>
</html>